# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 581)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.CamsgroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.CamsgroupBox.setEnabled(True)
        self.CamsgroupBox.setGeometry(QtCore.QRect(10, 40, 721, 81))
        self.CamsgroupBox.setObjectName("CamsgroupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.CamsgroupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 10, 721, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOpen = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnOpen.setEnabled(True)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout.addWidget(self.btnOpen)
        self.btnStart = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.btnSet = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSet.setObjectName("btnSet")
        self.horizontalLayout.addWidget(self.btnSet)
        self.btnMatch = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnMatch.setObjectName("btnMatch")
        self.horizontalLayout.addWidget(self.btnMatch)
        self.btnTest = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnTest.setObjectName("btnTest")
        self.horizontalLayout.addWidget(self.btnTest)
        self.btnClose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.btnHelp = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnHelp.setObjectName("btnHelp")
        self.horizontalLayout.addWidget(self.btnHelp)
        self.TitleLable = QtWidgets.QLabel(self.centralWidget)
        self.TitleLable.setGeometry(QtCore.QRect(260, 10, 201, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.TitleLable.setFont(font)
        self.TitleLable.setObjectName("TitleLable")
        self.RCamgroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.RCamgroupBox.setGeometry(QtCore.QRect(630, 120, 101, 401))
        self.RCamgroupBox.setObjectName("RCamgroupBox")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.RCamgroupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 91, 391))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnRCam = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnRCam.setObjectName("btnRCam")
        self.verticalLayout_3.addWidget(self.btnRCam)
        self.btnRImage = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnRImage.setObjectName("btnRImage")
        self.verticalLayout_3.addWidget(self.btnRImage)
        self.btnRState = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnRState.setObjectName("btnRState")
        self.verticalLayout_3.addWidget(self.btnRState)
        self.btnRSet = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnRSet.setObjectName("btnRSet")
        self.verticalLayout_3.addWidget(self.btnRSet)
        self.btnRMatch = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnRMatch.setObjectName("btnRMatch")
        self.verticalLayout_3.addWidget(self.btnRMatch)
        self.btnRTest = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnRTest.setObjectName("btnRTest")
        self.verticalLayout_3.addWidget(self.btnRTest)
        self.LCamgroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.LCamgroupBox.setGeometry(QtCore.QRect(10, 120, 101, 401))
        self.LCamgroupBox.setObjectName("LCamgroupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.LCamgroupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 91, 391))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnLCam = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnLCam.setObjectName("btnLCam")
        self.verticalLayout_2.addWidget(self.btnLCam)
        self.btnLImage = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnLImage.setObjectName("btnLImage")
        self.verticalLayout_2.addWidget(self.btnLImage)
        self.btnLState = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnLState.setObjectName("btnLState")
        self.verticalLayout_2.addWidget(self.btnLState)
        self.btnLSet = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnLSet.setObjectName("btnLSet")
        self.verticalLayout_2.addWidget(self.btnLSet)
        self.btnLMatch = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnLMatch.setObjectName("btnLMatch")
        self.verticalLayout_2.addWidget(self.btnLMatch)
        self.btnLTest = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnLTest.setObjectName("btnLTest")
        self.verticalLayout_2.addWidget(self.btnLTest)
        self.StategroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.StategroupBox.setGeometry(QtCore.QRect(120, 410, 501, 111))
        self.StategroupBox.setObjectName("StategroupBox")
        self.ResultLlabel = QtWidgets.QLabel(self.StategroupBox)
        self.ResultLlabel.setGeometry(QtCore.QRect(40, 30, 271, 41))
        self.ResultLlabel.setObjectName("ResultLlabel")
        self.LImageLable = QtWidgets.QLabel(self.centralWidget)
        self.LImageLable.setGeometry(QtCore.QRect(110, 130, 251, 271))
        self.LImageLable.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.LImageLable.setTextFormat(QtCore.Qt.AutoText)
        self.LImageLable.setObjectName("LImageLable")
        self.RImageLable = QtWidgets.QLabel(self.centralWidget)
        self.RImageLable.setGeometry(QtCore.QRect(370, 130, 251, 271))
        self.RImageLable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RImageLable.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.RImageLable.setObjectName("RImageLable")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 743, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionqidongxiangji = QtWidgets.QAction(MainWindow)
        self.actionqidongxiangji.setObjectName("actionqidongxiangji")
        self.actionCloseCamera = QtWidgets.QAction(MainWindow)
        self.actionCloseCamera.setObjectName("actionCloseCamera")
        self.actionTestCamera = QtWidgets.QAction(MainWindow)
        self.actionTestCamera.setObjectName("actionTestCamera")
        self.actionAboutCamera = QtWidgets.QAction(MainWindow)
        self.actionAboutCamera.setObjectName("actionAboutCamera")
        self.actionOpenImage = QtWidgets.QAction(MainWindow)
        self.actionOpenImage.setObjectName("actionOpenImage")
        self.actionEditImage = QtWidgets.QAction(MainWindow)
        self.actionEditImage.setObjectName("actionEditImage")
        self.actionSaveImage = QtWidgets.QAction(MainWindow)
        self.actionSaveImage.setObjectName("actionSaveImage")
        self.actionSIFT = QtWidgets.QAction(MainWindow)
        self.actionSIFT.setObjectName("actionSIFT")
        self.actionSURF = QtWidgets.QAction(MainWindow)
        self.actionSURF.setObjectName("actionSURF")
        self.actionCount = QtWidgets.QAction(MainWindow)
        self.actionCount.setObjectName("actionCount")
        self.menu.addAction(self.actionqidongxiangji)
        self.menu.addAction(self.actionCloseCamera)
        self.menu.addAction(self.actionTestCamera)
        self.menu.addAction(self.actionAboutCamera)
        self.menu_2.addAction(self.actionOpenImage)
        self.menu_2.addAction(self.actionEditImage)
        self.menu_2.addAction(self.actionSaveImage)
        self.menu_4.addAction(self.actionSIFT)
        self.menu_4.addAction(self.actionSURF)
        self.menu_5.addAction(self.actionCount)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CamsgroupBox.setTitle(_translate("MainWindow", "双相机操作"))
        self.btnOpen.setText(_translate("MainWindow", "启动相机"))
        self.btnStart.setText(_translate("MainWindow", "采集图像"))
        self.btnSet.setText(_translate("MainWindow", "双目标定"))
        self.btnMatch.setText(_translate("MainWindow", "立体匹配"))
        self.btnTest.setText(_translate("MainWindow", "双目测距"))
        self.btnClose.setText(_translate("MainWindow", "关闭相机"))
        self.btnHelp.setText(_translate("MainWindow", "帮助文档"))
        self.TitleLable.setText(_translate("MainWindow", "双目测量测试开发平台"))
        self.RCamgroupBox.setTitle(_translate("MainWindow", "右相机操作"))
        self.btnRCam.setText(_translate("MainWindow", "相机操作"))
        self.btnRImage.setText(_translate("MainWindow", "图像处理"))
        self.btnRState.setText(_translate("MainWindow", "特征监测"))
        self.btnRSet.setText(_translate("MainWindow", "相机标定"))
        self.btnRMatch.setText(_translate("MainWindow", "算法匹配"))
        self.btnRTest.setText(_translate("MainWindow", "单目测距"))
        self.LCamgroupBox.setTitle(_translate("MainWindow", "左相机操作"))
        self.btnLCam.setText(_translate("MainWindow", "相机操作"))
        self.btnLImage.setText(_translate("MainWindow", "图像处理"))
        self.btnLState.setText(_translate("MainWindow", "特征监测"))
        self.btnLSet.setText(_translate("MainWindow", "相机标定"))
        self.btnLMatch.setText(_translate("MainWindow", "算法匹配"))
        self.btnLTest.setText(_translate("MainWindow", "单目测距"))
        self.StategroupBox.setTitle(_translate("MainWindow", "检测结果及操作步骤"))
        self.ResultLlabel.setText(_translate("MainWindow", "结果显示"))
        self.LImageLable.setText(_translate("MainWindow", "左图像区域"))
        self.RImageLable.setText(_translate("MainWindow", "右图像区域"))
        self.menu.setTitle(_translate("MainWindow", "相机操作"))
        self.menu_2.setTitle(_translate("MainWindow", "图像操作"))
        self.menu_3.setTitle(_translate("MainWindow", "编辑处理"))
        self.menu_4.setTitle(_translate("MainWindow", "算法匹配"))
        self.menu_5.setTitle(_translate("MainWindow", "立体测距"))
        self.actionqidongxiangji.setText(_translate("MainWindow", "OpenCamera"))
        self.actionCloseCamera.setText(_translate("MainWindow", "CloseCamera"))
        self.actionTestCamera.setText(_translate("MainWindow", "TestCamera"))
        self.actionAboutCamera.setText(_translate("MainWindow", "AboutCamera"))
        self.actionOpenImage.setText(_translate("MainWindow", "OpenImage"))
        self.actionEditImage.setText(_translate("MainWindow", "EditImage"))
        self.actionSaveImage.setText(_translate("MainWindow", "SaveImage"))
        self.actionSIFT.setText(_translate("MainWindow", "SIFT"))
        self.actionSURF.setText(_translate("MainWindow", "SURF"))
        self.actionCount.setText(_translate("MainWindow", "Count"))

